### ISSUE TITLE
Click on playlist to play does not work

### ISSUE THREAD

**Issue by ashish173** [orizens/echoes-ng2#21]
Clicking on any playlist after I sign in does not add the songs to the queue. It throws a 403 forbidden error actually when I looked the response it says the request query was not formatted properly.

**Comment by ashish173** [comment]
@orizens I would love to work on it, in fact I am looking at the code right now, would love of you can give some pointers which might help me resolving this, thanks!!!

**Comment by orizens** [comment]
hi @ashish173 
thanks for reporting - this is indeed a bug.
